### ISSUE TITLE
Answer Update and Delete 답변을 찾을 수 없음

### ISSUE THREAD

**Issue by iseolin76** [theMomentTeam/the_moment-Server#104]
get으로 가져온 idx와 일치하는 idx로 요청을 날려도 답변을 찾을 수 없다고 뜹니다.
나머지는 다 잘됩니다.

**Comment by Johnjihwan** [comment]
delete 하고자 하는 answer가 ``user answer``인지 검증하는 로직에 대한 오류였습니다.
현재 issue 를 해결했습니다.
