### ISSUE TITLE
api 주소 변경 시 변경사항 공지

### ISSUE THREAD

**Issue by iseolin76** [theMomentTeam/the_moment-Server#76]
api 주소 변경 시에 어떤 주소가 어떻게 변경되었는 지 공지바랍니다.
-> 공지가 없어 혼란을 야기하기 때문입니다.

예시)
v1/uncomfortable -> v1/uncomfotable/top10으로 변경 후 변경되었다고 공지

**Comment by Johnjihwan** [comment]
네 알겠습니다.

기존 api 에 viewAll 하는 api가 누락되어,
viewAll 을 [v1/uncomfortable]로, top10 을 [v1/uncomfortable/top10] 으로 변경했습니다.
