### ISSUE TITLE
get 요청 없음

### ISSUE THREAD

**Issue by iseolin76** [theMomentTeam/the_moment-Server#82]
<img width="1520" alt="스크린샷 2021-05-05 오후 4 15 32" src="https://user-images.githubusercontent.com/65021545/117107829-35ebc480-adbd-11eb-8b87-4861eb398007.png">
get 요청이 없습니다.

**Comment by Johnjihwan** [comment]
현재 get 요청 api 추가로 인한 예외처리를 작업하는 중입니다.
이번주 안에 해당 서비스를 안정화를 시키고 알려드리겠습니다.
